### ISSUE TITLE
Query not working

### ISSUE THREAD

**Issue by ljames139** [ljames139/locallibrary#1]
Query

https://github.com/ljames139/locallibrary/blob/287d64edac27773bd3983689a5af3907867b70dd/src/catalog/views.py#L26

Where it renders

https://github.com/ljames139/locallibrary/blob/287d64edac27773bd3983689a5af3907867b70dd/src/catalog/templates/index.html#L22

**Comment by jb-0** [comment]
Will download repo and take a look at some point, but as a starter have you attempted this in command line? 

You will need to run:
python manage.py shell

Then import your models, so customise this:
![image](https://user-images.githubusercontent.com/39060614/86529228-facfea80-bea6-11ea-877c-b85fe9b00add.png)


Then you can test out this query manually in there. Would suggest starting by returning:
addams_books = Book.objects.filter(title__icontains='addams')

Explore the result of that, then add the count onto it.

**Comment by ljames139** [comment]
Error was incomplete context dictionary in the index view.

Revealed after troubleshooting using Python shell to check that database was returning correct results.
